name: ArcLinkDiscordBridge
main: com.signition.arclink.ArcLinkPlugin
version: ${project.version}
api-version: '1.21'
author: SignitionGPT
commands:
  discord:
    description: Send to Discord or manage bridge
    usage: /discord say <message> | /discord reload | /discord stats
    permission: arclink.use
  discordreload:
    description: Reload ArcLinkDiscordBridge config
    permission: arclink.admin
permissions:
  arclink.use:
    default: true
  arclink.admin:
    default: op
